# Generated by Django 4.2.20 on 2025-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('group', models.PositiveSmallIntegerField(choices=[(1, 'Мъжки и дамски дрехи'), (2, 'Електроника'), (3, 'Бижута')], default=1, help_text='продуктова група')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=40)),
            ],
        ),
    ]
